apiVersion: apps/v1
kind: Deployment
metadata:
  name: colorization-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: colorization-server
  template:
    metadata:
      labels:
        app: colorization-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - colorization-server
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: colorization-server
        image: osamasaqib1/colorization-server:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: colorization-server-service
spec:
  type: NodePort
  selector:
    app: colorization-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  sessionAffinity: None
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: colorization-server-destinationrule
spec:
  host: colorization-server-service
  subsets:
    - name: v1
      labels:
        app: colorization-server
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN

